# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 41f85cccfadc5d7dc7a45ae236e929d2b349298eeebcabeefec1e8409df3fc76030659bfc8df07dfb2bfe3e2f1fabba5d631c7df2f7a8136b70a87d2f97e640e

test:
  secret_key_base: e8533db0012f63ba201b06a2a2dc81025dde27024ed4295855d651c05572e0f46e3c3032a292d26c8b666332582a1a55ed2560c7a4fdd445e1c0482a75f7ef4c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
